add getServiceInfo method
SilinPavel/cloud-pipeline pull request #20
Opened 2019-08-29 16:06 UTC by ilya-ugr

2019-08-30 13:43 UTC, mzueva requested changes

2019-08-30 13:43 UTC, mzueva commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +        String nameOfService = "CloudPipeline";
move these values to application properties and inject them into service using `@Value` annotation

2019-08-30 13:43 UTC, mzueva commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +        List<String> listPathDataStorage = new ArrayList<>();
Let's use Stream API here:
`cloudPipelineAPIClient.loadAllDataStorages().stream().map( ... ).collect( ... )`
Also check that `cloudPipelineAPIClient.loadAllDataStorages()` doesn't return `null`. Convenient way to use it `ListUtils.emptyIfNull` method

2019-09-04 14:58 UTC, SilinPavel requested changes

2019-09-04 14:58 UTC, SilinPavel commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +        Stream<TesServiceInfo> tesServiceInfoStream = Stream.of(new TesServiceInfo())
I think that it is an over-engineering here, why you suppose that using streams here is a good way? Lets Create this object just with old fashion java:
````
TesServiceInfo tesServiceInfo = new TesServiceInfo();
tesServiceInfo.set....
tesServiceInfo.set....
tesServiceInfo.set....
return tesServiceInfo
````

2019-09-04 15:19 UTC, SilinPavel commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +@PropertySource("application.properties")
do we really need here this line? I believe that Spring will search this file for properties by default?

2019-09-04 15:29 UTC, SilinPavel commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +    @Value("cloud.pipeline.service.name")
you forget here ${}

2019-09-04 15:29 UTC, SilinPavel commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +    @Value("cloud.pipeline.doc")
same

2019-09-04 15:44 UTC, SilinPavel requested changes

2019-09-04 15:44 UTC, SilinPavel commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +        TesServiceInfo tesServiceInfo = new TesServiceInfo();
final

2019-09-04 15:44 UTC, SilinPavel commented on tes-adapter/src/main/java/com/epam/pipeline/tesadapter/service/TesTaskServiceImpl.java
> +        List<AbstractDataStorage> storageList = cloudPipelineAPIClient.loadAllDataStorages();
you don't need local variable here just do:
```
return ListUtils.emptyIfNull(cloudPipelineAPIClient.loadAllDataStorages())
              .stream()
              .map(storage -> storage.getPath())
              .collect(Collectors.toList());
```

2019-09-04 16:04 UTC, SilinPavel approved these changes

2019-09-06 08:30 UTC, merged